#! /bin/bash

sudo apt update
sudo apt search openjdk
apt install -y openjdk-11-jre-headless
java -version

echo "deb https://releases.jfrog.io/artifactory/artifactory-pro-debs xenial main" | sudo tee -a /etc/apt/sources.list;
wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -;
echo "deb https://releases.jfrog.io/artifactory/artifactory-debs focal main" | sudo tee -a /etc/apt/sources.list;
sudo apt-get update && sudo apt-get install jfrog-artifactory-oss

export ARTIFACTORY_PID=/var/run/artifactory.pid
cat /lib/systemd/system/artifactory.service
